spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?createDatabaseIfNotExist=true
    username: root
    password: Sudharsan@2003*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true